---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность попробовать принять участие в баттле без регистрации 
  - Пользователь должен иметь возможность отправлять сообщения в чате 
  - Пользователь должен иметь возоможность просматривать рейтинг пользователей
  - Пользователь должен иметь возоможность менять синтаксис языка в настройках
  - Пользователь должен иметь возоможность менять синтаксис языка в редакторе баттла
  - Пользователь должен иметь возможность менять тип звука в настройках
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На стартовой странице сайта должна быть кнопка смены языка
  - 
